image: haskell:8.6.3

cache:
  key: "all"  # Share cache to speed-up initial MR build
  paths:
    - .stack-root/
    - .stack-work/

stages:
  - test
  - test-script
  - build

variables:
  STACK_ROOT: "$CI_PROJECT_DIR/.stack-root"
  STACK_OPTIONS: "--no-install-ghc --system-ghc"

build-and-test:
  stage: test
  tags:
    - docker-executor
  only:
    refs:
      - merge_requests
      - master
      - production
    changes: &changes
      - Dockerfile
      - .dockerignore
      - .gitlab-ci.yml
      - morley.cabal
      - stack.yaml
      - test.bats
      - app/**/*
      - src/**/*
      - prelude/**/*
      - examples/EDSL/**/*
      - scripts/morley.sh
  script:
    - cp /usr/lib/gcc/x86_64-linux-gnu/6/crtbeginT.o /usr/lib/gcc/x86_64-linux-gnu/6/crtbeginT.o.orig
    - cp /usr/lib/gcc/x86_64-linux-gnu/6/crtbeginS.o /usr/lib/gcc/x86_64-linux-gnu/6/crtbeginT.o
    - stack $STACK_OPTIONS
        install morley
        --ghc-options '-Werror -optl-static -fPIC'
        --fast --local-bin-path tmp
        --test --no-run-tests
        --bench --no-run-benchmarks
        --haddock --no-haddock-deps
    - stack $STACK_OPTIONS
        test morley
    # Test EDSL examples
    - stack $STACK_OPTIONS
        --stack-yaml examples/EDSL/stack.yaml
        test
    - rm -rf "$STACK_ROOT/programs"  # Faster to download them again
  artifacts:
    paths:
      - tmp/morley

test-shell-script:
  image: alpine
  stage: test-script
  tags:
    - docker-executor
  dependencies:
    - build-and-test
  only:
    refs:
      - merge_requests
    changes: *changes
  script:
    - apk add bats
    - bats test.bats

build-docker-latest:
  image: docker:stable

  tags:
    - shell-executor

  before_script: &docker_login
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY


  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

  stage: build
  dependencies:
    - build-and-test
  only:
    refs:
      - master
    changes: *changes
  script: &docker_script
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

build-docker-production:
  image: docker:stable

  tags:
    - shell-executor

  before_script: *docker_login

  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:production

  stage: build
  dependencies:
    - build-and-test
  only:
    refs:
      - production
    changes: *changes
  script: *docker_script
