<<: !include "./hpack/module.yaml"

<<: *meta
name:                lorentz-contracts
version:             0.2.0.1
synopsis:            Set of Michelson contracts implemented in Lorentz eDSL.
description:
  Various contracts including simple examples, DS Token and other.
category:            Language
extra-source-files:
  - README.md

library:
  <<: *lorentz-lib-common

  build-tools:
    - morley:contract-discover

  dependencies:
    - bytestring
    - containers
    - data-default
    - indigo
    - fmt
    - hex-text
    - morley
    - morley-prelude
    - text
    - vinyl

executables:
  lorentz-contracts:
    <<: *exec-common

    dependencies:
      - containers
      - fmt
      - lorentz-contracts
      - morley
      - morley-prelude
      - optparse-applicative
      - text

tests:
  lorentz-contracts-test:
    <<: *test-common

    dependencies:
      - bytestring
      - containers
      - data-default
      - fmt
      - hspec
      - hspec-expectations
      - lorentz-contracts
      - morley
      - morley-prelude
      - QuickCheck
      - tasty
      - tasty-hspec
